// Generates /work's filter chips and its grouped card list as real,
// static DOM. Run: node scripts/build-work.mjs
//
// Replaces scripts/build-noscript.mjs, which wrote the same cards into a
// <noscript> block while js/render-work.js built the real thing at
// runtime. That split was the last CLS on the site (0.079): #work-app
// shipped empty, and the chip row and card list both landed after first
// paint, pushing everything down. Pre-rendering both means nothing is
// injected on load at all — js/render-work.js now attaches behaviour to
// elements that already exist and filters by hiding them, so the only
// layout changes are user-initiated (which don't count toward CLS) and
// a JS-disabled visitor gets the full list without a fallback copy.
//
// Cards are grouped by engagement type rather than led by filter rows
// (PRD v2 §4), and carry no capability tags — those are taxonomy, not
// content (§7, v1's F4). Colour does the categorising instead.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DOMAINS, CAPABILITIES, LISTED_CASES, TEMPLATES } from '../data/cases.js';
import { displayLabel, displayDateRange } from '../js/case-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const domainLabel = new Map(DOMAINS.map((d) => [d.slug, d.label]));

function escapeHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function recencyKey(c) {
  return c.dateEnd || c.dateStart || null;
}

function byRecency(cases) {
  return [...cases].sort((a, b) => {
    const ka = recencyKey(a);
    const kb = recencyKey(b);
    if (ka === null && kb === null) return 0;
    if (ka === null) return 1;
    if (kb === null) return -1;
    return kb.localeCompare(ka);
  });
}

function cardHtml(c) {
  const dateText = displayDateRange(c);
  const meta = [domainLabel.get(c.domain) || c.domain, displayLabel(c)];
  if (dateText) meta.push(dateText);
  return `          <a class="work-card" href="${c.slug}/" data-template="${c.template}" data-domain="${c.domain}" data-capabilities="${c.capabilities.join(' ')}">
            <p class="work-card-meta">${meta.map(escapeHtml).join(' · ')}</p>
            <h3 class="work-card-title">${escapeHtml(c.title)}</h3>
          </a>`;
}

function groupsHtml() {
  return Object.entries(TEMPLATES)
    .map(([key, template]) => {
      const inGroup = byRecency(LISTED_CASES.filter((c) => c.template === key));
      if (inGroup.length === 0) return null;
      return `      <section class="work-group" data-template="${key}">
        <header class="work-group-head">
          <h2>${escapeHtml(template.label)}</h2>
          <p class="work-group-blurb">${escapeHtml(template.blurb)}</p>
        </header>
        <div class="work-group-cards">
${inGroup.map(cardHtml).join('\n')}
        </div>
      </section>`;
    })
    .filter(Boolean)
    .join('\n\n');
}

function chipsHtml() {
  const row = (label, items, kind) => `        <div class="filter-row">
          <span class="filter-row-label">${label}</span>
          <div class="chip-scroll" role="group" aria-label="Filter by ${label.toLowerCase()}">
${items.map((i) => `            <button class="chip" type="button" data-kind="${kind}" data-slug="${i.slug}" aria-pressed="false">${escapeHtml(i.label)}</button>`).join('\n')}
          </div>
        </div>`;
  return `      <div class="filters">
${row('Domain', DOMAINS, 'domain')}
${row('Capability', CAPABILITIES, 'capability')}
      </div>
      <p class="work-count" data-total="${LISTED_CASES.length}">Showing all ${LISTED_CASES.length} engagements</p>`;
}

function replaceBetween(html, start, end, replacement, label) {
  const a = html.indexOf(start);
  const b = html.indexOf(end);
  if (a === -1 || b === -1) throw new Error(`${label} markers not found — did work/index.html change?`);
  return `${html.slice(0, a + start.length)}\n${replacement}\n      ${html.slice(b)}`;
}

function run() {
  const p = join(ROOT, 'work', 'index.html');
  let html = readFileSync(p, 'utf8');
  html = replaceBetween(html,
    '<!-- WORK-FILTERS:START — generated by scripts/build-work.mjs, do not hand-edit -->',
    '<!-- WORK-FILTERS:END -->', chipsHtml(), 'WORK-FILTERS');
  html = replaceBetween(html,
    '<!-- WORK-GROUPS:START — generated by scripts/build-work.mjs, do not hand-edit -->',
    '<!-- WORK-GROUPS:END -->', groupsHtml(), 'WORK-GROUPS');
  writeFileSync(p, html);

  const counts = Object.keys(TEMPLATES)
    .map((k) => `${k}:${LISTED_CASES.filter((c) => c.template === k).length}`)
    .join(' ');
  console.log(`Regenerated /work: ${LISTED_CASES.length} listed cases grouped by engagement type (${counts}), chips pre-rendered.`);
}

run();
