// Generates the "Selected work" case cards on the home page from
// data/cases.js. Run: node scripts/build-home.mjs
//
// The three featured cases are a fixed, deliberate choice (not "most
// recent" or "all P0s") — the WRD's flagship picks, one per visual
// treatment (lead/medium/quiet). Which three cases appear is a curation
// decision made in markup (FEATURED_SLUGS below); their title/org/domain/
// date text is generated from the data so a future edit to any of those
// facts can't silently drift out of sync with what the case page itself
// says, the way the old hand-typed noscript fallbacks once did.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DOMAINS, LISTED_CASES } from '../data/cases.js';
import { displayLabel, displayDateRange } from '../js/case-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const domainLabel = new Map(DOMAINS.map((d) => [d.slug, d.label]));

// slug -> which visual treatment it gets (see css/home.css .work-card--*)
const FEATURED = [
  { slug: 'situation-room-osun-election', treatment: 'lead' },
  { slug: 'africa-infrastructure-roundtable', treatment: 'medium' },
  { slug: 'osun-tech-festival', treatment: 'quiet' },
];

function escapeHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function metaLine(caseObj) {
  const dateText = displayDateRange(caseObj);
  const parts = [domainLabel.get(caseObj.domain) || caseObj.domain, displayLabel(caseObj)];
  if (dateText) parts.push(dateText);
  return parts.map(escapeHtml).join(' · ');
}

function cardHtml({ slug, treatment }) {
  const caseObj = LISTED_CASES.find((c) => c.slug === slug);
  if (!caseObj) {
    throw new Error(`build-home.mjs: featured slug "${slug}" is not a listed case in data/cases.js — either it does not exist, or it is listed: false and therefore has no page to link to.`);
  }
  const href = `work/${caseObj.slug}/`;
  const meta = metaLine(caseObj);
  const title = escapeHtml(caseObj.title);

  if (treatment === 'lead') {
    return `      <a href="${href}" class="work-card work-card--lead">
        <p class="work-card-meta">${meta}</p>
        <h3 class="work-card-title">${title}</h3>
        <span class="work-card-cta">Read the case</span>
      </a>`;
  }
  if (treatment === 'medium') {
    return `      <a href="${href}" class="work-card work-card--medium">
        <p class="work-card-meta">${meta}</p>
        <h3 class="work-card-title">${title}</h3>
      </a>`;
  }
  return `      <a href="${href}" class="work-card work-card--quiet">
        <p class="work-card-meta">${meta}</p>
        <h3 class="work-card-title">${title}</h3>
      </a>`;
}

function replaceBetweenMarkers(html, start, end, replacement, label) {
  const startIdx = html.indexOf(start);
  const endIdx = html.indexOf(end);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`${label} markers not found — did index.html's structure change?`);
  }
  const before = html.slice(0, startIdx + start.length);
  const after = html.slice(endIdx);
  return `${before}\n${replacement}\n      ${after}`;
}

function run() {
  const homePath = join(ROOT, 'index.html');
  const html = readFileSync(homePath, 'utf8');
  const cardsHtml = FEATURED.map(cardHtml).join('\n\n');
  const updated = replaceBetweenMarkers(
    html,
    '<!-- FEATURED-WORK:START — generated by scripts/build-home.mjs, do not hand-edit -->',
    '<!-- FEATURED-WORK:END -->',
    cardsHtml,
    'index.html FEATURED-WORK'
  );
  writeFileSync(homePath, updated);
  console.log(`Regenerated index.html's featured work section (${FEATURED.length} cases: ${FEATURED.map((f) => f.slug).join(', ')}).`);
}

run();
